name: Update v1 Tag

on:
  push:
    tags:
      - 'v1.*.*'
  release:
    types: [published]

permissions:
  contents: write
  issues: write

jobs:
  update-v1-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v1.') && contains(github.ref, '.')
    
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏷️ Update v1 tag
        run: |
          # Extract version from tag
          NEW_VERSION="${GITHUB_REF#refs/tags/}"
          echo "New version: $NEW_VERSION"
          
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Delete old v1 tag locally if it exists
          git tag -d v1 || true
          
          # Create new v1 tag pointing to the new release
          git tag v1 "$NEW_VERSION"
          
          # Push the updated tag (safe method)
          git push origin --delete v1 || true
          git push origin v1
          
          echo "✅ Updated v1 tag to point to $NEW_VERSION"

      - name: 📝 Log success
        run: |
          echo "✅ Successfully updated v1 tag to point to ${GITHUB_REF#refs/tags/}"
          echo "Users can now reference workflows using @v1 to get the latest 1.x version"
